name: Pulumi
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

on:
  push:
    branches:  
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test-and-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::052848974346:role/piers-github-role
          role-session-name: githubactions
          aws-region: eu-west-1

      - name: Pulumi Version
        run: pulumi version

      - name: Login to Pulumi
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi About
        run: pulumi about

      - name: Pulumi preview
        run: pulumi preview
        env:
          PULUMI_STACK: dev
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}